version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: evasiongusto-web
    ports:
      - "8080:80"
    volumes:
      # Bind mount the current directory to nginx html folder
      - .:/usr/share/nginx/html:ro
      # Optional: Custom nginx config for better development
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    labels:
      - "description=Évasion Gusto Website Development Server"
