// Menu page: recipe detail lightbox + PDF export.
// Recipe cards themselves are static HTML (generated by inject-menu-cards.js)
// so this only needs to wire up interactions, not render content.

(function () {
    'use strict';

    function openRecipeLightbox(imgEl) {
        const lightbox = document.getElementById('recipe-lightbox');
        const lightboxImg = document.getElementById('recipe-lightbox-img');
        const lightboxTitle = document.getElementById('recipe-lightbox-title');

        const webp = imgEl.dataset.detailWebp;
        const jpg = imgEl.dataset.detailJpg;
        lightboxImg.src = (webp && supportsWebp()) ? webp : jpg;
        lightboxImg.alt = imgEl.dataset.detailTitle || '';
        lightboxTitle.textContent = imgEl.dataset.detailTitle || '';

        lightbox.style.display = 'flex';
        document.body.classList.add('lightbox-open');
    }

    function closeRecipeLightbox() {
        document.getElementById('recipe-lightbox').style.display = 'none';
        document.body.classList.remove('lightbox-open');
    }
    window.closeRecipeLightbox = closeRecipeLightbox;

    let webpSupport = null;
    function supportsWebp() {
        if (webpSupport !== null) return webpSupport;
        const canvas = document.createElement('canvas');
        webpSupport = canvas.toDataURL('image/webp').indexOf('image/webp') === 5;
        return webpSupport;
    }

    document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('.recipe-card-img').forEach((img) => {
            img.addEventListener('click', () => openRecipeLightbox(img));
            img.addEventListener('keydown', (e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                    e.preventDefault();
                    openRecipeLightbox(img);
                }
            });
        });

        const lightbox = document.getElementById('recipe-lightbox');
        lightbox.addEventListener('click', (e) => {
            if (e.target === lightbox) closeRecipeLightbox();
        });
        document.addEventListener('keydown', (e) => {
            if (e.key === 'Escape' && lightbox.style.display === 'flex') {
                closeRecipeLightbox();
            }
        });

        const downloadBtn = document.getElementById('download-menu-pdf');
        if (downloadBtn) {
            downloadBtn.addEventListener('click', downloadMenuPdf);
        }
    });

    // The PDF must reflect every card, but lazy-loaded images below the
    // fold may still be showing their blurred LQIP placeholder at click
    // time - force them all to their full-size source first.
    function forceLoadAllRecipeImages() {
        const images = document.querySelectorAll('.recipe-card-img[data-src]');
        const loads = Array.from(images).map((img) => new Promise((resolve) => {
            const picture = img.closest('picture');
            const source = picture && picture.querySelector('source[data-srcset]');
            if (source && source.dataset.srcset) {
                source.srcset = source.dataset.srcset;
                source.removeAttribute('data-srcset');
            }

            const fullImage = new Image();
            fullImage.onload = () => {
                img.src = img.dataset.src;
                img.removeAttribute('data-src');
                img.classList.add('lazy-loaded');
                resolve();
            };
            fullImage.onerror = resolve;
            fullImage.src = img.dataset.src;
        }));
        return Promise.all(loads);
    }

    function downloadMenuPdf() {
        const downloadBtn = document.getElementById('download-menu-pdf');
        const grid = document.getElementById('menu-grid');
        const recipeCount = grid.querySelectorAll('.recipe-card').length;

        downloadBtn.disabled = true;
        const originalText = downloadBtn.textContent;
        downloadBtn.textContent = '...';

        forceLoadAllRecipeImages().then(() => window.html2pdf()
            .set({
                margin: 10,
                filename: 'menu-evasion-gusto.pdf',
                image: { type: 'jpeg', quality: 0.92 },
                html2canvas: { scale: 2, useCORS: true },
                jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
                pagebreak: { mode: ['css', 'avoid-all'], avoid: '.recipe-card' },
            })
            .from(grid)
            .save()
            .then(() => {
                if (typeof gtag === 'function') {
                    gtag('event', 'download_menu_pdf', { recipe_count: recipeCount });
                }
            })
            .finally(() => {
                downloadBtn.disabled = false;
                downloadBtn.textContent = originalText;
            })
        );
    }
})();
